"""add users update

Revision ID: dfcf0db3c321
Revises: 4eea1c971aae
Create Date: 2025-04-27 22:31:59.277399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfcf0db3c321"
down_revision: Union[str, None] = "4eea1c971aae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(length=200), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
